### ISSUE TITLE
Year, Actors, Directors

### ISSUE THREAD

**Issue by jief666** [theapache64/movie_db#1]
Hi,
thanks for that project. I switched to it from Omdb. Easy and works, bravo.

Would be nice to have the year, actors and directors.

Thanks.

**Comment by theapache64** [comment]
Hey jief666, I've added year, stars and directors.

**Comment by jief666** [comment]
Thanks. My project is updated. It works.
Great.

**Comment by theapache64** [comment]
:) :+1:
