### ISSUE TITLE
Site for sale!

### ISSUE THREAD

**Issue by ThoughtFool** [theapache64/movie_db#14]
It appears as if your site is up for sale.  Will you be redirecting your tutorials and GitHub links elsewhere? BTW... Really clear and easy to understand tutorials! Thanks

Info below... 
![image](https://user-images.githubusercontent.com/16545043/38158925-c6c1e8e6-346b-11e8-95cd-1aa15ecf65d2.png)

**Comment by theapache64** [comment]
Primary domain replaced with http://theapache64.com (y)
