### ISSUE TITLE
Still going ?

### ISSUE THREAD

**Issue by jief666** [theapache64/movie_db#7]
Hi,

after the title of the project it's written "[deceased]", and the server URL doesn't work anymore.

But I see you were still working on it few days ago. Did you stop ? Do you plan to have that up again ?

Regards.
Jief

**Comment by theapache64** [comment]
Yes, am working on it jief. I hope, i can release it soon

**Comment by jief666** [comment]
Nice, thanks.

**Comment by theapache64** [comment]
Hey jief, New version's live! :) check it out, and let me know if there's any error.

**Comment by jief666** [comment]
Hi, great thanks.
However, this URL : http://theapache64.xyz:8080/movie_db/search?keyword=tt3337092 cannot find any movie. I saw in your code (few days ago) that look in google first. I tried in google and the first link is right, but I know google result are not in same order for everyone.
Maybe an url like http://theapache64.xyz:8080/movie_db/search?code=[CODE] could directly go to URL http://www.imdb.com/title/[CODE].
If you prefer, I could implement that in a fork, making a pull request when it's done, but not very soon.
Regards.

**Comment by theapache64** [comment]
Hi jief, I had to change some parts of the algorithm for better performance. while i was modifying the code, i also implemented the feature you requested. From now on, if the keyword get matched with imdb regex (tt\d{7}), it'll not search in google, and will directly hit imdb.com. Thank you so much for your wonderful idea. :)

**Comment by jief666** [comment]
Personally, I would have implemented an other another key. "code" instead of "keyword" for example, because assuming a imdb code is and will always match regex (tt\d{7}) is unreliable over time.
That said, for what I'm doing, I'm fine with that.
The issue #4 still there though. http://theapache64.xyz:8080/movie_db/search?keyword=tt3337092 bring back "Lara de Miguel, Manuel Feijóo.\" /><meta property=\"og:description\" in the stars field.
